name: Run Discord Bot

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -U discord.py

    - name: Run Bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        TARGET_VOICE_CHANNEL_ID: ${{ secrets.TARGET_VOICE_CHANNEL_ID }}
        TARGET_TEXT_CHANNEL_ID: ${{ secrets.TARGET_TEXT_CHANNEL_ID }}
      run: python main.py